[technote]
id = "SITCOMTN-126"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-126.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-126"
github_default_branch = "main"
date_created = 2024-04-23T04:26:19Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[[technote.authors]]
name.given = "Alysha"
name.family = "Shugart"
internal_id = "shugarta"
orcid = "https://orcid.org/0009-0000-6778-7168"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "Avenida Juan Cisternas 1500, Chile, "

[[technote.authors]]
name = {given = "Craig", family = "Lage"}
internal_id = "lagec"
orcid = "https://orcid.org/0000-0002-9601-345X"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"

